eclipse/microprofile-bom

CONTRIBUTING.adoc
NOTICE
README.adoc
pom.xml

Re-do of #1 to remove the IP-Validation issues...

Initial drop of README, NOTICE, CONTRIBUTING, and pom.xml

---

README.adoc

Minor update to README to show we're still in SNAPSHOT mode for the 1.1 release...

update README to indicate SNAPSHOT (for now...)

---

README.adoc
pom.xml
spec/NOTICE
spec/pom.xml
spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/license-alv2.asciidoc
spec/src/main/asciidoc/microprofile-bom-spec.asciidoc
spec/src/main/resources/META-INF/LICENSE
spec/src/main/resources/META-INF/NOTICE

Created spec document in preparation for MP 1.1 release.

created spec doc

---

pom.xml

We should change the style of the BOM

---

README.adoc

This updates the README.adoc to be more explicit about the usage requirements for the current style of BOM.

Clarify current usage, issue #11

---

README.adoc
pom.xml
spec/pom.xml

Getting rid of SNAPSHOT and moving towards the real release.

Changes to bom for 1.1.0 release

---

.editorconfig
.gitattributes
.gitignore
perform_release/deploy_to_maven_central.sh
perform_release/prepare_release.sh
spec/src/main/asciidoc/microprofile-spec.asciidoc

Besides the infrastructure changes, I also updated the spec per Issue #19 -- since there was an ip-validation issue with that Issue.

Initial drop of release prep scripts for bom component

---

perform_release/deploy_to_maven_central.sh
pom.xml

Autorelease in Maven Central is false by default now so that we may properly review artifacts.

Fixed script for maven central deploy

---

NOTICE
README.adoc
pom.xml
spec/pom.xml

Instead of microprofile-bom, just let's use microprofile, as in MP 1.0 - http://search.maven.org/#artifactdetails%7Cio.microprofile%7Cmicroprofile%7C1.0.0%7Cpom

Changed artifact name simply to microprofile

---

NOTICE
README.adoc
pom.xml
spec/pom.xml
spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/microprofile-spec.asciidoc
spec/src/main/asciidoc/required-apis.asciidoc

Updated the MP 1.2 spec to include the new propose feature updates.  Also, did a bit more cleanup to get rid of the "bom" designation.

Updating MP 1.2 to include new features

---

pom.xml
spec/pom.xml

change to 2 digit version

---

pom.xml

Upgrading to the final release of MP Config 1.1

---

pom.xml

Add MP-JWT 1.0 to the bom

---

pom.xml

Update metrics to 1.0

---

pom.xml

Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

add FT to MP 1.2

---

pom.xml

Update health to 1.0

---

spec/src/main/asciidoc/microprofile-spec.asciidoc
spec/src/main/asciidoc/required-apis.asciidoc

Final comments before Final 1.2 release???

Kevin rc2 comments

---

spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/required-apis.asciidoc

Signed-off-by: Don Bourne <dbourne@ca.ibm.com>

Fix name in references to metrics.  Fixes #45.

---

spec/src/main/asciidoc/required-apis.asciidoc

There will eventually be a JCP link in there like for JAX-RS and others, so added that now but with a clear statement it is in processes.

Note on Config JSR

---

pom.xml

update pom.xml in prep for updated release process

---

pom.xml
spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/required-apis.asciidoc

Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>
Fixes #56

Bump the version of Metrics to 1.1

---

pom.xml
spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/microprofile-spec.asciidoc
spec/src/main/asciidoc/required-apis.asciidoc

Spec updates and pom updates in prep for MP 1.3...
Resolves #53

Spec updates 2

---

spec/pom.xml
spec/src/main/asciidoc/microprofile-spec.asciidoc

Making the spec build process more generalized and consistent with the rest of the specs.

parameterize the spec build process

---

pom.xml
spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/required-apis.asciidoc

Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>

#57 add config 1.2

---

pom.xml
spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/required-apis.asciidoc

Signed-off-by: Steve Fontes <steve.m.fontes@gmail.com>
For https://github.com/eclipse/microprofile-bom/issues/55

Add opentracing to bom

---

spec/src/main/asciidoc/microprofile-spec.asciidoc

Just trying to make the microprofile.io site a bit more readable.  Still not perfect, but it's better...

Add some line breaks in spec
